ineuron python assignment 8

In [2]:
#program to add two matrices
import numpy as np
x=[[1,2,3,4],
   [4,5,6,7],
  [1,6,9,8]]
y=[[10,20,30,40],
   [50,60,70,80],
  [40,80,70,50]]
result=np.array(x)+np.array(y)
print(result)

[[11 22 33 44]
 [54 65 76 87]
 [41 86 79 58]]


In [5]:
#program to multiply two matrices
A=[[1,2,3],
   [4,5,6],
  [1,6,9]]
B=[[11,22,33,44],
 [54,65,76,87],
 [41,86,79,58]]
result=[[0,0,0,0],[0,0,0,0],[0,0,0,0]]
result=np.dot(A,B)
for p in result:
    print(p)
    

[242 410 422 392]
[560 929 986 959]
[ 704 1186 1200 1088]


In [8]:
#program to transpose a matrix
A=np.array([[1,2,3],[3,4,6]])
print("The matric is:",A)
A_T=A.transpose()
print("The Transpose Matrix:",A_T)

The matric is: [[1 2 3]
 [3 4 6]]
The Transpose Matrix: [[1 3]
 [2 4]
 [3 6]]


In [10]:
#set words in an alphabetical oder

my_str=input("Enter the string:")
words=[word.lower() for word in my_str.split()]
words.sort()
print("The Sorted words are:")
for word in words:
    print(word)
    

Enter the string: this is a alphabet


The Sorted words are:
a
alphabet
is
this


In [15]:
#remove punctuation  from string
import string
text="I am favourite,How Can I Help You??"
print("The String with punctuation:",text)
translating=str.maketrans('','',string.punctuation)
new_string=text.translate(translating)
print("remove punctuation:",new_string)

The String with punctuation: I am favourite,How Can I Help You??
remove punctuation: I am favouriteHow Can I Help You
